name: mibitracker-client-dev
channels:
- conda-forge
- defaults
dependencies:
- coverage=4.2=py36_0
- jupyter=1.0.0
- matplotlib=3.0.2
- mock=2.0.0
- numpy=1.13.3
- pip=18.0=py36_1
- pylint=1.8.4=py36_0
- pytest=3.2.1=py36_0
- python=3.6.3=0
- requests=2.20.1=py36_0
- scikit-image=0.13.0=np113py36_0
- setuptools=40.4.0
- sphinx=1.6.3=py36_0
- sphinx-argparse=0.2.2
